### ISSUE TITLE
Allow customization of separator char

### ISSUE THREAD

**Issue by alexanderjeurissen** [alexanderjeurissen/tmux-world-clock#1]
Currently we use the `|` character to separate the different timezones, however the end user might desire to use a different separation character. as such introducing a `@world_clock_tz_sep` option might be desirable.

**Comment by eb0815** [comment]
I just submitted a pull request to make a few things customisable (trigger for me was the output format). Among these, the separator was an easy fix.

**Comment by alexanderjeurissen** [comment]
Thank you so much I just merged it. Great contribution !!
